name: PlatformIO Build

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: PlatformIO installieren
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build
        run: pio run
