name: PlatformIO Build

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: PlatformIO installieren
        run: |
          python -m pip install --upgrade pip
          python -m pip install platformio

      - name: PlatformIO-Version anzeigen
        run: pio --version

      - name: Projekt bauen
        run: pio run -e esp32-4827S043R
